### ISSUE TITLE
Cannot add inetOrgPerson entry with binary userCertificate

### ISSUE THREAD

**Issue by guidow** [cannatag/ldap3#280]
Somehow, I cannot add an entry with objectClass ```inetOrgPerson``` to an LDAP server using ldap3:

    >>> der_cert = open("../temp/test.der", "rb").read()
    >>> type(der_cert)
    <class 'bytes'>
    >>> server = Server("localhost", get_info=ALL)                                                                                                 
    >>> conn = Connection(server, user="cn=Manager,dc=nb-winkelmann,dc=hornetsecurity,dc=com", password="secret")
    >>> conn.bind()
    >>> conn.add("cn=testuser,dc=hornetsecurity,dc=com", "inetOrgPerson", {"cn": "testuser", "sn": "testuser", "userCertificate": der_cert})
    False
    >>> conn.result
    {'type': 'addResponse', 'description': 'undefinedAttributeType', 'dn': '', 'referrals': None, 'message': 'userCertificate: requires ;binary transfer', 'result': 17}
    >>> conn.add("cn=testuser,dc=hornetsecurity,dc=com", "inetOrgPerson", {"cn": "testuser", "sn": "testuser", "userCertificate;binary": der_cert})
    Traceback (most recent call last):
    File "<console>", line 1, in <module>
    File "/home/guido/virtualenvs/smime_manager/lib/python3.4/site-packages/ldap3/core/connection.py", line 867, in add
        raise LDAPAttributeError('invalid attribute type ' + attribute_name)
    ldap3.core.exceptions.LDAPAttributeError: invalid attribute type userCertificate;binary

Adding this entry without the ```userCertificate``` attribute works fine. So does adding it with OpenLDAP's ```ldapadd``` tool with the certificate included.
Adding the entry without the certificate and then adding just the attribute later with ```Connection.modify``` ends with the same error.

Am I missing something here? Apparently, this attribute needs to be transmitted in binary mode, and somehow I need to signal the ldap3 library to do just that. Appending ```;binary``` to the attribute name does not do the trick, though. (It does when reading.)

**Comment by cannatag** [comment]
Can you try with the latest code in dev? It should solve this issue. 
Also you could also use the check_bytes() function in the ldap3.utils.conv module.

**Comment by cannatag** [comment]
I've added checks to encode only well known utf8 syntaxes and types. Will be released in 2.2.

**Comment by guidow** [comment]
No, the problem is still there even with newest code from dev.

**Comment by cannatag** [comment]
Can you check it again? Now the tags in attribute names are not checked against the schema.

**Comment by guidow** [comment]
Still no change at all at 234097b20e7c6fb0f6d09c973de0c74b38a03e7a

**Comment by guidow** [comment]
Correction: There is a change now, the exception is now raised in a different place than before:

    >>> conn.add("cn=testuser,dc=hornetsecurity,dc=com", "inetOrgPerson", {"cn": "testuser", "sn": "testuser", "userCertificate;binary": der_cert})                                                                                             
    Traceback (most recent call last):                                                                                                                           
    File "<console>", line 1, in <module>                                                                                                                      
    File "/home/guido/ldap3/ldap3/core/connection.py", line 891, in add                                                                                        
        request = add_operation(dn, attributes, self.auto_encode, self.server.schema if self.server else None)                                                   
    File "/home/guido/ldap3/ldap3/operation/add.py", line 49, in add_operation                                                                                 
        vals.setComponentByPosition(0, prepare_for_sending(validate_attribute_value(schema, attribute, attributes[attribute], auto_encode)))                                                                                                                                           
    File "/home/guido/ldap3/ldap3/protocol/convert.py", line 136, in validate_attribute_value                                                                  
        raise LDAPAttributeError('invalid attribute ' + name)                                                                                                    
    ldap3.core.exceptions.LDAPAttributeError: invalid attribute userCertificate;binary

**Comment by cannatag** [comment]
Could you check it again?

**Comment by guidow** [comment]
Seems to work now, at least for add. I haven't tried modify yet.

**Comment by guidow** [comment]
Modify does not work:

    >>> der_cert = open("../temp/test.der", "rb").read()
    >>> type(der_cert)
    <class 'bytes'>
    >>> from ldap3 import Server, Connection, ALL, MODIFY_REPLACE
    >>> server = Server("localhost", get_info=ALL)
    >>> conn = Connection(server, user="cn=Manager,dc=nb-winkelmann,dc=hornetsecurity,dc=com", password="secret")
    >>> conn.bind()
    True
    >>> conn.modify("cn=testuser,dc=hornetsecurity,dc=com", {"userCertificate;binary": [(MODIFY_REPLACE, der_cert)]})
    Traceback (most recent call last):
    File "<console>", line 1, in <module>
    File "/home/guido/ldap3/ldap3/core/connection.py", line 1004, in modify
        change = changes[attribute_name]
    KeyError: 'userCertificate'

**Comment by cannatag** [comment]
Sorry for annoying you, can you try again with the updated code in dev? Please try both add() and modify(), I've slightly changed how tags are managed and sent to the server in the request.

**Comment by guidow** [comment]
Both add and modify work now in a simple test.

**Comment by cannatag** [comment]
included in v2.2.0.
