### ISSUE TITLE
entryDN attribute returned when operational attributes not requested

### ISSUE THREAD

**Issue by kpinc** [cannatag/ldap3#787]
After calling:

```
server = ldap3.Server.from_definition(
        server_name,
        'examples/dummy_server_info.json',
        'examples/dummy_server_schema.json')
connection = ldap3.Connection(
        server, user=user, password=password,
        return_empty_attributes=False,
	client_strategy=ldap3.MOCK_SYNC)
```
and then adding an entry, a search operation

```
connection.search(
	dn, '(objectclass=*)', attributes=ldap3.ALL_ATTRIBUTES)
```
 returns the entryDN attribute in:

```
connection.response['entries'][0]['attributes']
```
"entryDN" is an operational attribute and should not be returned.

(I haven't tried without the MOCK_SYNC strategy.)

**Comment by cannatag** [comment]
This should have been fixed, can you check the code in dev?

Thanks,
Giovanni

**Comment by kpinc** [comment]
On Fri, 21 Feb 2020 09:23:55 -0800
Giovanni Cannata <notifications@github.com> wrote:

> This should have been fixed, can you check the code in dev?

I tried dev just now and unless I made some mistake it's
not fixed.  Looking at the dev branch on github I see
the hardcoded 'objectClass'....

Regards,

Karl <kop@karlpinc.com>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein

**Comment by kpinc** [comment]
On Fri, 21 Feb 2020 12:43:02 -0600
"Karl O. Pinc" <kop@karlpinc.com> wrote:

> On Fri, 21 Feb 2020 09:23:55 -0800
> Giovanni Cannata <notifications@github.com> wrote:
> 
> > This should have been fixed, can you check the code in dev?  
> 
> I tried dev just now and unless I made some mistake it's
> not fixed.  Looking at the dev branch on github I see
> the hardcoded 'objectClass'....

Oops.  I did make a mistake.  Please wait while I check again.

Thanks.

Regards,

Karl <kop@karlpinc.com>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein

**Comment by kpinc** [comment]
On Fri, 21 Feb 2020 12:52:33 -0600
"Karl O. Pinc" <kop@karlpinc.com> wrote:

> Oops.  I did make a mistake.  Please wait while I check again.

Yes.  This is fixed.  (I was looking at the wrong bug.)

Thanks for the help.

Regards,

Karl <kop@karlpinc.com>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein

**Comment by cannatag** [comment]
Fixed in ldap3 v2.7.
